basePath: /api/v1
definitions:
  main.AuthCredentials:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
  main.Option:
    properties:
      explanation:
        type: string
      id:
        type: string
      isCorrect:
        type: boolean
      text:
        type: string
    type: object
  main.Question:
    properties:
      difficulty:
        type: string
      id:
        type: string
      options:
        items:
          $ref: '#/definitions/main.Option'
        type: array
      text:
        type: string
      topic:
        type: string
    type: object
  main.ScoreDTO:
    properties:
      attemptedAt:
        type: string
      createdAt:
        type: string
      difficulty:
        type: string
      id:
        type: integer
      points:
        type: integer
      topic:
        type: string
      total:
        type: integer
      updatedAt:
        type: string
      userId:
        type: integer
    type: object
  main.ScoreSubmission:
    properties:
      difficulty:
        type: string
      points:
        minimum: 0
        type: integer
      topic:
        type: string
      total:
        type: integer
    required:
    - difficulty
    - points
    - topic
    - total
    type: object
  main.SubmitAnswerBody:
    properties:
      answerId:
        type: string
      questionId:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is the API for the EchoTech learning platform.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: EchoTech API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticates a user and returns a JWT
      parameters:
      - description: User login credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/main.AuthCredentials'
      produces:
      - application/json
      responses:
        "200":
          description: Login successful, token provided
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid input or invalid credentials
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Invalid credentials
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login an existing user
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Creates a new user account
      parameters:
      - description: User registration credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/main.AuthCredentials'
      produces:
      - application/json
      responses:
        "201":
          description: User created successfully (userId in response)
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid input or user already exists
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register a new user
      tags:
      - auth
  /difficulties:
    get:
      consumes:
      - application/json
      description: Get a list of available difficulties
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              items:
                type: string
              type: array
            type: object
      summary: Get available difficulties
      tags:
      - quiz
  /ping:
    get:
      consumes:
      - application/json
      description: get "pong" response to check if server is alive
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Ping the server
      tags:
      - health
  /questions/{difficulty}/{topic}:
    get:
      consumes:
      - application/json
      description: Get a list of questions for a specific difficulty and topic
      parameters:
      - description: Difficulty level (easy, medium, hard)
        in: path
        name: difficulty
        required: true
        type: string
      - description: Topic name
        in: path
        name: topic
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              items:
                $ref: '#/definitions/main.Question'
              type: array
            type: object
      summary: Get questions by difficulty and topic
      tags:
      - quiz
  /scores:
    post:
      consumes:
      - application/json
      description: Saves a quiz score for the authenticated user
      parameters:
      - description: Score details
        in: body
        name: score
        required: true
        schema:
          $ref: '#/definitions/main.ScoreSubmission'
      produces:
      - application/json
      responses:
        "201":
          description: Score saved successfully
          schema:
            $ref: '#/definitions/main.ScoreDTO'
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Submit a user's quiz score
      tags:
      - scores
  /submit:
    post:
      consumes:
      - application/json
      description: Submit an answer and get feedback
      parameters:
      - description: Submission Payload
        in: body
        name: submission
        required: true
        schema:
          $ref: '#/definitions/main.SubmitAnswerBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Submit an answer to a question
      tags:
      - quiz
  /topics:
    get:
      consumes:
      - application/json
      description: Get a list of available topics
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              items:
                type: string
              type: array
            type: object
      summary: Get available topics
      tags:
      - quiz
  /users/me/scores:
    get:
      description: Retrieves all quiz scores for the currently logged-in user
      produces:
      - application/json
      responses:
        "200":
          description: List of user scores
          schema:
            items:
              $ref: '#/definitions/main.ScoreDTO'
            type: array
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get scores for the authenticated user
      tags:
      - scores
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
